# Travis Continuous Integration Configuration File
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      cache: apt
      env: DOCKER_IMAGE=ubuntu:trusty
    - os: linux
      dist: trusty
      sudo: required
      cache: apt
      env: DOCKER_IMAGE=ubuntu:xenial
    - os: linux
      dist: trusty
      sudo: required
      cache: apt
      env: DOCKER_IMAGE=osrf/ubuntu_armhf:trusty
    - os: linux
      dist: trusty
      sudo: required
      cache: apt
      env: DOCKER_IMAGE=osrf/ubuntu_armhf:xenial
    - os: linux
      dist: trusty
      sudo: required
      cache: apt
      env: DOCKER_IMAGE=osrf/ubuntu_arm64:trusty
    - os: linux
      dist: trusty
      sudo: required
      cache: apt
      env: DOCKER_IMAGE=osrf/ubuntu_arm64:xenial
    - os: linux
      dist: trusty
      sudo: required
      cache: apt
      env: DOCKER_IMAGE=debian:jessie
    - os: linux
      dist: trusty
      sudo: required
      cache: apt
      env: DOCKER_IMAGE=osrf/debian_arm64:jessie
    - os: osx
env:
  global:
    - MAKEFLAGS='-j4'
notifications:
  email:
    recipients:
      - euslisp@jsk.t.u-tokyo.ac.jp
    on_success: always #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
before_install: # Use this to prepare the system to install prerequisites or dependencies
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Define some config vars
install:
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - if [[ "$DOCKER_IMAGE" == *"arm"* ]]; then sudo apt-get install -y -qq qemu-user-static; fi
  - if [[ "$DOCKER_IMAGE" == *"arm"* ]]; then git clone http://github.com/euslisp/jskeus ${HOME}/jskeus; fi
script:
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run --rm -i -v $HOME:$HOME -e "TRAVIS_OS_NAME=$TRAVIS_OS_NAME" -e "CI_SOURCE_PATH=$CI_SOURCE_PATH" -e "HOME=$HOME" -e "MAKEFLAGS=$MAKEFLAGS" -t $DOCKER_IMAGE sh -c "cd $CI_SOURCE_PATH; ./.travis.sh"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then  source ./.travis.sh; fi
after_failure:
  - echo "failure"
after_success:
  - (cd eus/doc/latex;  make)
  - (cd eus/doc/jlatex; make)
